export const negativeEmotions = {
  angry: {
    name: 'Angry',
    icon: '😠',
    color: 'bg-red-100',
    subEmotions: [
      { name: 'Enraged', triggers: ['Injustice', 'Violation', 'Disrespect'] },
      { name: 'Malicious', triggers: ['Intent to harm', 'Cruelty', 'Spite'] },
      { name: 'Infuriated', triggers: ['Extreme anger', 'Provocation', 'Outrage'] },
      { name: 'Violent', triggers: ['Physical aggression', 'Force', 'Destruction'] },
      { name: 'Vindictive', triggers: ['Revenge', 'Getting even', 'Payback'] },
      { name: 'Furious', triggers: ['Intense anger', 'Rage', 'Outrage'] },
      { name: 'Repulsed', triggers: ['Disgust', 'Aversion', 'Rejection'] },
      { name: 'Seething', triggers: ['Suppressed rage', 'Internal anger', 'Tension'] },
      { name: 'Scornful', triggers: ['Contempt', 'Disdain', 'Derision'] },
      { name: 'Hitting', triggers: ['Physical aggression', 'Violence', 'Force'] },
      { name: 'Yelling', triggers: ['Verbal aggression', 'Shouting', 'Outbursts'] },
      { name: 'Revengeful', triggers: ['Vengeance', 'Retaliation', 'Payback'] },
      { name: 'Hostile', triggers: ['Antagonism', 'Opposition', 'Aggression'] },
      { name: 'Insulting', triggers: ['Verbal attacks', 'Disrespect', 'Mockery'] },
      { name: 'Swearing', triggers: ['Verbal expression', 'Frustration', 'Anger'] },
      { name: 'Condemning', triggers: ['Judgment', 'Criticism', 'Blame'] },
      { name: 'Offensive', triggers: ['Causing hurt', 'Disrespect', 'Rudeness'] },
      { name: 'Aggressive', triggers: ['Confrontation', 'Force', 'Attack'] },
      { name: 'Bitter', triggers: ['Resentment', 'Past hurts', 'Grudges'] },
      { name: 'Loud', triggers: ['Volume', 'Intensity', 'Expression'] },
      { name: 'Sarcastic', triggers: ['Mockery', 'Indirect anger', 'Contempt'] },
      { name: 'Frustrated', triggers: ['Blocked goals', 'Obstacles', 'Limitations'] },
      { name: 'Resentful', triggers: ['Unfairness', 'Perceived wrongs', 'Bitterness'] },
      { name: 'Critical', triggers: ['Judgment', 'Finding fault', 'Disapproval'] },
      { name: 'Mean', triggers: ['Cruelty', 'Nastiness', 'Hostility'] },
      { name: 'Sadistic', triggers: ['Enjoying pain', 'Cruelty', 'Control'] },
      { name: 'Spiteful', triggers: ['Malice', 'Desire to hurt', 'Revenge'] },
      { name: 'Jealous', triggers: ['Comparison', 'Envy', 'Insecurity'] },
      { name: 'Short-tempered', triggers: ['Quick anger', 'Impatience', 'Irritability'] },
      { name: 'Mad', triggers: ['Anger', 'Rage', 'Fury'] },
      { name: 'Cross', triggers: ['Irritation', 'Annoyance', 'Displeasure'] },
      { name: 'Retaliating', triggers: ['Getting even', 'Revenge', 'Response'] },
      { name: 'Overbearing', triggers: ['Domination', 'Control', 'Intimidation'] },
      { name: 'Incensed', triggers: ['Outrage', 'Extreme anger', 'Fury'] },
      { name: 'Upset', triggers: ['Disturbance', 'Distress', 'Agitation'] },
      { name: 'Irritated', triggers: ['Annoyance', 'Agitation', 'Frustration'] },
      { name: 'Controlling', triggers: ['Dominance', 'Power', 'Manipulation'] },
      { name: 'Agitated', triggers: ['Restlessness', 'Disturbance', 'Tension'] },
      { name: 'Antagonistic', triggers: ['Opposition', 'Hostility', 'Conflict'] },
      { name: 'Reprimanding', triggers: ['Scolding', 'Criticism', 'Correction'] },
      { name: 'Envious', triggers: ['Wanting others have', 'Comparison', 'Lack'] },
      { name: 'Reactive', triggers: ['Quick response', 'Impulsivity', 'Triggers'] },
      { name: 'Abrupt', triggers: ['Sudden', 'Harsh', 'Sharp'] },
      { name: 'Quarrelsome', triggers: ['Arguments', 'Conflict', 'Disputes'] },
      { name: 'Stubborn', triggers: ['Inflexibility', 'Resistance', 'Obstinacy'] },
      { name: 'Rebellious', triggers: ['Defiance', 'Opposition', 'Resistance'] },
      { name: 'Exasperated', triggers: ['Frustration', 'Irritation', 'Fed up'] },
      { name: 'Impatient', triggers: ['Waiting', 'Delay', 'Urgency'] },
      { name: 'Contrary', triggers: ['Opposition', 'Disagreement', 'Resistance'] },
      { name: 'Disrespectful', triggers: ['Rudeness', 'Contempt', 'Inconsideration'] },
      { name: 'Unpleasant', triggers: ['Nastiness', 'Disagreeable', 'Difficult'] },
      { name: 'Annoyed', triggers: ['Irritation', 'Bothered', 'Disturbed'] },
      { name: 'Dictatorial', triggers: ['Authoritarian', 'Controlling', 'Demanding'] },
      { name: 'Sharp', triggers: ['Harsh words', 'Cutting remarks', 'Intensity'] },
      { name: 'Snapping', triggers: ['Quick reaction', 'Harsh response', 'Irritation'] }
    ]
  },
  depressed: {
    name: 'Depressed',
    icon: '😔',
    color: 'bg-gray-100',
    subEmotions: [
      { name: 'Suicidal', triggers: ['Hopelessness', 'Deep despair', 'Self-hatred'] },
      { name: 'Directionless', triggers: ['Lack of purpose', 'Confusion', 'Lost'] },
      { name: 'Empty', triggers: ['Void', 'Numbness', 'Disconnection'] },
      { name: 'Desperate', triggers: ['Hopelessness', 'Last resort', 'Crisis'] },
      { name: 'Despairing', triggers: ['Deep hopelessness', 'Giving up', 'Loss'] },
      { name: 'In Hell', triggers: ['Extreme suffering', 'Deep pain', 'Torment'] },
      { name: 'Alienated', triggers: ['Isolation', 'Disconnection', 'Otherness'] },
      { name: 'Miserable', triggers: ['Deep unhappiness', 'Suffering', 'Pain'] },
      { name: 'Masochistic', triggers: ['Self-punishment', 'Self-harm', 'Pain-seeking'] },
      { name: 'Despicable', triggers: ['Self-hatred', 'Worthlessness', 'Disgust'] },
      { name: 'Self-hating', triggers: ['Self-loathing', 'Self-disgust', 'Self-rejection'] },
      { name: 'Self-critical', triggers: ['Self-judgment', 'Perfectionism', 'Inadequacy'] },
      { name: 'Self-deprecating', triggers: ['Self-diminishment', 'Self-mockery', 'Low self-worth'] },
      { name: 'Stuck', triggers: ['Immobility', 'No way out', 'Trapped'] },
      { name: 'Ashamed', triggers: ['Shame', 'Humiliation', 'Unworthiness'] },
      { name: 'Exhausted', triggers: ['Fatigue', 'Depletion', 'No energy'] },
      { name: 'Lousy', triggers: ['Bad feelings', 'Worthlessness', 'Negativity'] },
      { name: 'Tired', triggers: ['Physical fatigue', 'Mental exhaustion', 'Depletion'] },
      { name: 'Despondent', triggers: ['Loss of hope', 'Discouragement', 'Giving up'] },
      { name: 'Disheartened', triggers: ['Disappointment', 'Loss of hope', 'Discouragement'] },
      { name: 'Down', triggers: ['Low mood', 'Sadness', 'Depression'] },
      { name: 'Disappointed', triggers: ['Unmet expectations', 'Letdown', 'Failure'] },
      { name: 'Discouraged', triggers: ['Loss of confidence', 'Setbacks', 'Defeat'] },
      { name: 'Powerless', triggers: ['Helplessness', 'No control', 'Weakness'] },
      { name: 'Hopeless', triggers: ['No future', 'Despair', 'Giving up'] },
      { name: 'Grouchy', triggers: ['Irritability', 'Bad mood', 'Discontent'] },
      { name: 'Guilty', triggers: ['Self-blame', 'Remorse', 'Shame'] },
      { name: 'Dissatisfied', triggers: ['Discontent', 'Unfulfillment', 'Wanting'] },
      { name: 'Sulky', triggers: ['Bad mood', 'Pouting', 'Withdrawal'] },
      { name: 'Low', triggers: ['Down mood', 'Depression', 'Heaviness'] },
      { name: 'Bad', triggers: ['Negative feelings', 'Unworthiness', 'Wrong'] },
      { name: 'Pessimistic', triggers: ['Negative outlook', 'Cynicism', 'No hope'] },
      { name: 'Dejected', triggers: ['Disappointment', 'Rejection', 'Failure'] },
      { name: 'Glum', triggers: ['Melancholy', 'Sadness', 'Depression'] },
      { name: 'Cheerless', triggers: ['No joy', 'Flatness', 'Depression'] },
      { name: 'Rotten', triggers: ['Bad feelings', 'Worthlessness', 'Disgust'] },
      { name: 'Crabby', triggers: ['Irritability', 'Bad mood', 'Grumpiness'] },
      { name: 'Resistant', triggers: ['Opposition', 'Blocking', 'Unwillingness'] },
      { name: 'Punishing', triggers: ['Self-punishment', 'Criticism', 'Harshness'] },
      { name: 'Morose', triggers: ['Gloominess', 'Depression', 'Sullenness'] },
      { name: 'Cranky', triggers: ['Irritability', 'Bad mood', 'Grumpiness'] },
      { name: 'Grumpy', triggers: ['Bad mood', 'Irritability', 'Discontent'] },
      { name: 'Burdened', triggers: ['Heavy load', 'Overwhelm', 'Pressure'] },
      { name: 'Negative', triggers: ['Pessimism', 'Criticism', 'Dark outlook'] },
      { name: 'Closed', triggers: ['Shut down', 'Withdrawal', 'Protection'] },
      { name: 'Contracted', triggers: ['Tension', 'Withdrawal', 'Protection'] },
      { name: 'Tight', triggers: ['Tension', 'Stress', 'Constriction'] },
      { name: 'Blocked', triggers: ['Stuck energy', 'No flow', 'Obstruction'] },
      { name: 'Moody', triggers: ['Changing emotions', 'Irritability', 'Instability'] },
      { name: 'Out of sorts', triggers: ['Discomfort', 'Unease', 'Off balance'] },
      { name: 'No energy', triggers: ['Fatigue', 'Depletion', 'Exhaustion'] },
      { name: 'Touchy', triggers: ['Sensitivity', 'Irritability', 'Reactivity'] },
      { name: 'Haggard', triggers: ['Exhaustion', 'Worn out', 'Strain'] },
      { name: 'Drawn', triggers: ['Fatigue', 'Strain', 'Exhaustion'] },
      { name: 'Slumped', triggers: ['Depression', 'Defeat', 'Low energy'] },
      { name: 'Slouching', triggers: ['Poor posture', 'Low energy', 'Depression'] },
      { name: 'Achy', triggers: ['Physical pain', 'Discomfort', 'Soreness'] },
      { name: 'Self-loathing', triggers: ['Self-hatred', 'Disgust', 'Unworthiness'] },
      { name: 'Crummy', triggers: ['Bad feelings', 'Poor state', 'Unwellness'] },
      { name: 'Wretched', triggers: ['Misery', 'Suffering', 'Despair'] }
    ]
  },
  confused: {
    name: 'Confused',
    icon: '😕',
    color: 'bg-purple-100',
    subEmotions: [
      { name: 'Lost', triggers: ['Disorientation', 'No direction', 'Uncertainty'] },
      { name: 'Disoriented', triggers: ['Lost direction', 'Confusion', 'Chaos'] },
      { name: 'Off-kilter', triggers: ['Imbalance', 'Disruption', 'Instability'] },
      { name: 'Frenzied', triggers: ['Chaos', 'Overwhelm', 'Panic'] },
      { name: 'Indecisive', triggers: ['Choice paralysis', 'Uncertainty', 'Doubt'] },
      { name: 'Doubtful', triggers: ['Uncertainty', 'Lack of confidence', 'Question'] },
      { name: 'Uncertain', triggers: ['Doubt', 'Unclear path', 'Hesitation'] },
      { name: 'Distrustful', triggers: ['Suspicion', 'Doubt', 'Mistrust'] },
      { name: 'Misgiving', triggers: ['Doubt', 'Unease', 'Concern'] },
      { name: 'Unsure', triggers: ['Self-doubt', 'Hesitation', 'Uncertainty'] },
      { name: 'Uneasy', triggers: ['Discomfort', 'Anxiety', 'Worry'] },
      { name: 'Tense', triggers: ['Stress', 'Pressure', 'Anxiety'] },
      { name: 'Stressed', triggers: ['Pressure', 'Overwhelm', 'Demands'] },
      { name: 'Argumentative', triggers: ['Conflict', 'Disagreement', 'Opposition'] },
      { name: 'Authoritative', triggers: ['Control', 'Power', 'Dominance'] },
      { name: 'Condescending', triggers: ['Superiority', 'Arrogance', 'Dismissiveness'] },
      { name: 'Embarrassed', triggers: ['Shame', 'Self-consciousness', 'Awkwardness'] },
      { name: 'Comparing', triggers: ['Self-doubt', 'Competition', 'Inadequacy'] },
      { name: 'Dishonest', triggers: ['Deception', 'Lying', 'Hiding'] },
      { name: 'Demanding', triggers: ['Control', 'Pressure', 'Expectations'] },
      { name: 'Blushing', triggers: ['Embarrassment', 'Attention', 'Self-consciousness'] },
      { name: 'Awkward', triggers: ['Social discomfort', 'Clumsiness', 'Uncertainty'] }
    ]
  },
  helpless: {
    name: 'Helpless',
    icon: '😰',
    color: 'bg-cyan-100',
    subEmotions: [
      { name: 'Distraught', triggers: ['Extreme upset', 'Distress', 'Anguish'] },
      { name: 'Distressed', triggers: ['Suffering', 'Pain', 'Anguish'] },
      { name: 'Shut down', triggers: ['Overwhelm', 'Withdrawal', 'Shutdown'] },
      { name: 'Alone', triggers: ['Isolation', 'Loneliness', 'Abandonment'] },
      { name: 'Fatigued', triggers: ['Exhaustion', 'Tiredness', 'Depletion'] },
      { name: 'Useless', triggers: ['Worthlessness', 'Inadequacy', 'Failure'] },
      { name: 'Inferior', triggers: ['Low self-worth', 'Comparison', 'Inadequacy'] },
      { name: 'Inept', triggers: ['Incompetence', 'Failure', 'Inadequacy'] },
      { name: 'Cut off', triggers: ['Isolation', 'Disconnection', 'Separation'] },
      { name: 'Sick', triggers: ['Physical illness', 'Discomfort', 'Pain'] },
      { name: 'Nauseated', triggers: ['Physical discomfort', 'Sickness', 'Disgust'] },
      { name: 'Fidgety', triggers: ['Restlessness', 'Anxiety', 'Nervousness'] },
      { name: 'Trembling', triggers: ['Fear', 'Anxiety', 'Nervousness'] },
      { name: 'Squirming', triggers: ['Discomfort', 'Restlessness', 'Anxiety'] },
      { name: 'Jittery', triggers: ['Nervousness', 'Anxiety', 'Restlessness'] }
    ]
  },
  indifferent: {
    name: 'Indifferent',
    icon: '😐',
    color: 'bg-slate-100',
    subEmotions: [
      { name: 'Lifeless', triggers: ['Lack of energy', 'Depression', 'Emptiness'] },
      { name: 'Unresponsive', triggers: ['Withdrawal', 'Shutdown', 'Disconnection'] },
      { name: 'Insensitive', triggers: ['Lack of empathy', 'Coldness', 'Detachment'] },
      { name: 'Dull', triggers: ['Lack of interest', 'Boredom', 'Flatness'] },
      { name: 'Weary', triggers: ['Tiredness', 'Exhaustion', 'Fatigue'] },
      { name: 'Preoccupied', triggers: ['Distraction', 'Mental absence', 'Focus elsewhere'] },
      { name: 'Slow', triggers: ['Lethargy', 'Low energy', 'Sluggishness'] },
      { name: 'Sluggish', triggers: ['Low energy', 'Slowness', 'Lethargy'] },
      { name: 'Blasé', triggers: ['Indifference', 'Lack of interest', 'Apathy'] },
      { name: 'Blank', triggers: ['Empty mind', 'Lack of thought', 'Numbness'] }
    ]
  },
  afraid: {
    name: 'Afraid',
    icon: '😨',
    color: 'bg-yellow-100',
    subEmotions: [
      { name: 'Terrified', triggers: ['Extreme fear', 'Danger', 'Threat'] },
      { name: 'Petrified', triggers: ['Paralyzed fear', 'Terror', 'Freeze'] },
      { name: 'Panicked', triggers: ['Emergency', 'Loss of control', 'Crisis'] },
      { name: 'Frozen', triggers: ['Shock', 'Immobility', 'Fear response'] },
      { name: 'Threatened', triggers: ['Danger', 'Risk', 'Intimidation'] },
      { name: 'Hateful', triggers: ['Aversion', 'Disgust', 'Strong dislike'] },
      { name: 'Agoraphobic', triggers: ['Open spaces', 'Crowds', 'Public places'] },
      { name: 'Fearful', triggers: ['Danger', 'Unknown', 'Threat'] },
      { name: 'Suspicious', triggers: ['Distrust', 'Doubt', 'Skepticism'] },
      { name: 'Rigid', triggers: ['Control', 'Inflexibility', 'Fear'] },
      { name: 'Phobic', triggers: ['Specific fears', 'Irrational fear', 'Avoidance'] },
      { name: 'Disturbed', triggers: ['Unease', 'Discomfort', 'Distress'] },
      { name: 'Disrupted', triggers: ['Chaos', 'Disorder', 'Upheaval'] },
      { name: 'Anxious', triggers: ['Worry', 'Future fears', 'Uncertainty'] },
      { name: 'Alarmed', triggers: ['Sudden fear', 'Warning', 'Alert'] },
      { name: 'Dreading', triggers: ['Future fear', 'Anticipation', 'Worry'] },
      { name: 'Attacking', triggers: ['Defense', 'Fear response', 'Aggression'] },
      { name: 'Intimidated', triggers: ['Power imbalance', 'Threat', 'Fear'] },
      { name: 'Nervous', triggers: ['Anxiety', 'Unease', 'Tension'] },
      { name: 'Scared', triggers: ['Fear', 'Danger', 'Threat'] },
      { name: 'Worried', triggers: ['Concern', 'Anxiety', 'Future fears'] },
      { name: 'Frightened', triggers: ['Fear', 'Alarm', 'Danger'] },
      { name: 'Timid', triggers: ['Shyness', 'Hesitation', 'Fear'] },
      { name: 'Shaky', triggers: ['Physical fear', 'Nervousness', 'Trembling'] },
      { name: 'Restless', triggers: ['Anxiety', 'Unease', 'Agitation'] },
      { name: 'Cowardly', triggers: ['Fear response', 'Avoidance', 'Weakness'] },
      { name: 'Insecure', triggers: ['Self-doubt', 'Uncertainty', 'Fear'] },
      { name: 'Wary', triggers: ['Caution', 'Suspicion', 'Alert'] },
      { name: 'Menaced', triggers: ['Threat', 'Intimidation', 'Fear'] },
      { name: 'Uptight', triggers: ['Tension', 'Stress', 'Anxiety'] },
      { name: 'Apprehensive', triggers: ['Worry', 'Concern', 'Anticipation'] },
      { name: 'Defensive', triggers: ['Protection', 'Guard', 'Fear'] },
      { name: 'Guarded', triggers: ['Protection', 'Caution', 'Defense'] },
      { name: 'Troubled', triggers: ['Worry', 'Concern', 'Distress'] },
      { name: 'Self-absorbed', triggers: ['Internal focus', 'Self-concern', 'Withdrawal'] },
      { name: 'Intolerant', triggers: ['Rejection', 'Judgment', 'Rigidity'] },
      { name: 'Avoiding', triggers: ['Escape', 'Evasion', 'Fear response'] },
      { name: 'Unwelcoming', triggers: ['Closure', 'Rejection', 'Defense'] },
      { name: 'Unbending', triggers: ['Rigidity', 'Inflexibility', 'Control'] },
      { name: 'Paranoid', triggers: ['Extreme suspicion', 'Fear', 'Distrust'] },
      { name: 'Inhibited', triggers: ['Restraint', 'Control', 'Fear'] },
      { name: 'Immobile', triggers: ['Paralysis', 'Freeze', 'Fear response'] },
      { name: 'Attached', triggers: ['Dependency', 'Fear of loss', 'Clinging'] },
      { name: 'Prejudiced', triggers: ['Bias', 'Pre-judgment', 'Fear of different'] },
      { name: 'Self-conscious', triggers: ['Social anxiety', 'Self-awareness', 'Judgment fear'] }
    ]
  },
  hurt: {
    name: 'Hurt',
    icon: '💔',
    color: 'bg-pink-100',
    subEmotions: [
      { name: 'Tormented', triggers: ['Deep pain', 'Mental anguish', 'Suffering'] },
      { name: 'Pained', triggers: ['Emotional hurt', 'Suffering', 'Distress'] },
      { name: 'Tortured', triggers: ['Extreme pain', 'Agony', 'Torment'] },
      { name: 'Agonized', triggers: ['Intense suffering', 'Deep pain', 'Distress'] },
      { name: 'Crushed', triggers: ['Devastation', 'Heartbreak', 'Complete loss'] },
      { name: 'Deprived', triggers: ['Loss', 'Denial', 'Lack'] },
      { name: 'Rejected', triggers: ['Exclusion', 'Abandonment', 'Unwanted'] },
      { name: 'Humiliated', triggers: ['Shame', 'Embarrassment', 'Degradation'] },
      { name: 'Insulted', triggers: ['Disrespect', 'Offense', 'Mockery'] },
      { name: 'Injured', triggers: ['Emotional wound', 'Harm', 'Damage'] },
      { name: 'Offended', triggers: ['Disrespect', 'Slight', 'Insult'] },
      { name: 'Afflicted', triggers: ['Suffering', 'Pain', 'Distress'] },
      { name: 'Aching', triggers: ['Emotional pain', 'Longing', 'Hurt'] },
      { name: 'Victimized', triggers: ['Powerlessness', 'Exploitation', 'Abuse'] },
      { name: 'Heartbroken', triggers: ['Loss', 'Betrayal', 'Deep grief'] },
      { name: 'Appalled', triggers: ['Shock', 'Horror', 'Dismay'] },
      { name: 'Wronged', triggers: ['Injustice', 'Unfairness', 'Mistreatment'] },
      { name: 'Withdrawn', triggers: ['Retreat', 'Isolation', 'Self-protection'] },
      { name: 'Miffed', triggers: ['Minor offense', 'Annoyance', 'Slight'] },
      { name: 'Indignant', triggers: ['Righteous anger', 'Unfairness', 'Offense'] },
      { name: 'Suffering', triggers: ['Pain', 'Anguish', 'Distress'] },
      { name: 'Distant', triggers: ['Emotional withdrawal', 'Detachment', 'Separation'] },
      { name: 'Invaded', triggers: ['Boundary violation', 'Intrusion', 'Privacy breach'] },
      { name: 'Bulldozed', triggers: ['Overwhelmed', 'Forced', 'Powerless'] },
      { name: 'Bullied', triggers: ['Intimidation', 'Harassment', 'Power abuse'] },
      { name: 'Secretive', triggers: ['Hidden pain', 'Protection', 'Privacy'] },
      { name: 'Slighted', triggers: ['Minor rejection', 'Disregard', 'Dismissal'] },
      { name: 'Smothered', triggers: ['Overwhelm', 'Suffocation', 'Control'] },
      { name: 'Belittled', triggers: ['Diminishment', 'Condescension', 'Disrespect'] }
    ]
  },
  sad: {
    name: 'Sad',
    icon: '😢',
    color: 'bg-blue-100',
    subEmotions: [
      { name: 'Anguished', triggers: ['Deep pain', 'Suffering', 'Distress'] },
      { name: 'Desolate', triggers: ['Emptiness', 'Abandonment', 'Complete loss'] },
      { name: 'Devastated', triggers: ['Complete loss', 'Destruction', 'Ruin'] },
      { name: 'Grieved', triggers: ['Loss', 'Death', 'Deep sorrow'] },
      { name: 'Tearful', triggers: ['Emotional release', 'Pain', 'Crying'] },
      { name: 'Sorrowful', triggers: ['Deep sadness', 'Mourning', 'Grief'] },
      { name: 'Unhappy', triggers: ['Discontent', 'Dissatisfaction', 'Pain'] },
      { name: 'Lonely', triggers: ['Isolation', 'Abandonment', 'Disconnection'] },
      { name: 'Mournful', triggers: ['Loss', 'Grief', 'Deep sadness'] },
      { name: 'Dismayed', triggers: ['Disappointment', 'Shock', 'Distress'] },
      { name: 'Downhearted', triggers: ['Depression', 'Discouragement', 'Low spirits'] },
      { name: 'Oversensitive', triggers: ['Emotional reactivity', 'Vulnerability', 'Pain'] },
      { name: 'Remorseful', triggers: ['Regret', 'Guilt', 'Shame'] },
      { name: 'Sullen', triggers: ['Bad mood', 'Withdrawal', 'Gloom'] },
      { name: 'Sour', triggers: ['Bitterness', 'Negativity', 'Displeasure'] },
      { name: 'Self-castigating', triggers: ['Self-blame', 'Self-punishment', 'Guilt'] },
      { name: 'Unworthy', triggers: ['Low self-worth', 'Shame', 'Inadequacy'] },
      { name: 'Fragile', triggers: ['Vulnerability', 'Weakness', 'Sensitivity'] },
      { name: 'Disconnected', triggers: ['Isolation', 'Detachment', 'Separation'] },
      { name: 'Blindsided', triggers: ['Unexpected pain', 'Shock', 'Surprise'] },
      { name: 'Discontented', triggers: ['Unhappiness', 'Dissatisfaction', 'Restlessness'] },
      { name: 'Crying', triggers: ['Emotional release', 'Pain', 'Tears'] },
      { name: 'Groaning', triggers: ['Pain expression', 'Suffering', 'Distress'] },
      { name: 'Moaning', triggers: ['Pain expression', 'Complaint', 'Suffering'] },
      { name: 'Forlorn', triggers: ['Abandonment', 'Loneliness', 'Desolation'] }
    ]
  },
  judgmental: {
    name: 'Judgmental',
    icon: '🧐',
    color: 'bg-amber-100',
    subEmotions: [
      { name: 'Stony', triggers: ['Coldness', 'Hardness', 'Emotional distance'] },
      { name: 'Hurtful', triggers: ['Causing pain', 'Cruelty', 'Meanness'] },
      { name: 'Brutal', triggers: ['Harshness', 'Cruelty', 'Violence'] },
      { name: 'Combative', triggers: ['Fighting', 'Aggression', 'Conflict'] },
      { name: 'Attacked', triggers: ['Defense', 'Victimization', 'Aggression'] },
      { name: 'Tactless', triggers: ['Insensitivity', 'Bluntness', 'Rudeness'] },
      { name: 'Glaring', triggers: ['Visual criticism', 'Hostility', 'Disapproval'] },
      { name: 'Disgusted', triggers: ['Revulsion', 'Contempt', 'Aversion'] },
      { name: 'Ranting', triggers: ['Angry speech', 'Complaint', 'Criticism'] },
      { name: 'Scolding', triggers: ['Criticism', 'Reprimand', 'Correction'] },
      { name: 'Obsessive', triggers: ['Control', 'Perfectionism', 'Fixation'] },
      { name: 'Serious', triggers: ['Gravity', 'Intensity', 'Lack of humor'] },
      { name: 'Stern', triggers: ['Strictness', 'Authority', 'Severity'] },
      { name: 'Frowning', triggers: ['Disapproval', 'Displeasure', 'Concern'] },
      { name: 'Recoiling', triggers: ['Aversion', 'Withdrawal', 'Disgust'] },
      { name: 'Unfair', triggers: ['Injustice', 'Bias', 'Discrimination'] },
      { name: 'Bossy', triggers: ['Control', 'Dominance', 'Authority'] },
      { name: 'Stilted', triggers: ['Rigidity', 'Formality', 'Stiffness'] },
      { name: 'Stiff', triggers: ['Inflexibility', 'Rigidity', 'Formality'] },
      { name: 'Pushy', triggers: ['Aggression', 'Force', 'Pressure'] },
      { name: 'Neglectful', triggers: ['Inattention', 'Carelessness', 'Disregard'] },
      { name: 'Stonewalling', triggers: ['Blocking', 'Silence', 'Withdrawal'] },
      { name: 'Rude', triggers: ['Disrespect', 'Inconsideration', 'Offense'] },
      { name: 'Shrill', triggers: ['Harsh tone', 'Intensity', 'Aggression'] },
      { name: 'Hard', triggers: ['Inflexibility', 'Harshness', 'Severity'] },
      { name: 'Fake', triggers: ['Inauthentic', 'Pretense', 'Deception'] },
      { name: 'Phony', triggers: ['Insincerity', 'Pretense', 'False'] },
      { name: 'Shallow', triggers: ['Superficiality', 'Lack of depth', 'Emptiness'] },
      { name: 'Territorial', triggers: ['Possessiveness', 'Control', 'Defense'] },
      { name: 'Complaining', triggers: ['Criticism', 'Dissatisfaction', 'Negativity'] },
      { name: 'Blunt', triggers: ['Direct criticism', 'Harshness', 'Tactlessness'] },
      { name: 'Arrogant', triggers: ['Superiority', 'Pride', 'Condescension'] },
      { name: 'Superior', triggers: ['Looking down', 'Pride', 'Condescension'] },
      { name: 'Faultfinding', triggers: ['Criticism', 'Perfectionism', 'Negativity'] }
    ]
  }
}; 